export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const REMOVE_ACCESS_TOKEN = "REMOVE_ACCESS_TOKEN"
export const GET_USER = "GET_USER"
export const GET_USER_STARRED = "GET_USER_STARRED"

export const LOADING = "LOADING"
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

export const FILE_LOADING = 'FILELOADING'
export const FILE_LOADING_COMPLETE = 'FILE_LOADING_COMPLETE'

export const TREE_LOADING = 'TREE_LOADING'
export const TREE_LOADING_COMPLETE = 'TREE_LOADING_COMPLETE'

export const GET_STARRED_REPO_FILE = 'GET_STARRED_REPO_FILE'
export const GET_STARRED_REPO_README = 'GET_STARRED_REPO_README'

export const SET_FILE_PATH = 'SET_FILE_PATH'

// export const RENDER_MARKDOWN_RAW = 'RENDER_MARKDOWN_RAW'

export const GET_STARRED_REPO_TREE = 'GET_STARRED_REPO_TREE'