export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN"
export const REMOVE_ACCESS_TOKEN = "REMOVE_ACCESS_TOKEN"
export const GET_USER = "GET_USER"
export const GET_USER_STARRED = "GET_USER_STARRED"

export const LOADING = "LOADING"
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

export const FILE_LOADING = 'FILELOADING'
export const FILE_LOADING_COMPLETE = 'FILE_LOADING_COMPLETE'

export const GET_STARRED_REPO_FILE = 'GET_STARRED_REPO_FILE'
export const GET_STARRED_REPO_README = 'GET_STARRED_REPO_README'

// export const RENDER_MARKDOWN_RAW = 'RENDER_MARKDOWN_RAW'